gpu_list:
    - 3
seed: null
dump_path: './outputs/'
defaults:
    - data: iwcd_electron
    - data/dataset: iwcd_cnn_short
    - model: regression
    - model/feature_extractor: resnet18
    - model/regression_alg: linear
    - engine: regression
    - tasks/train: train_resnet
    - optimizers@tasks.train.optimizers: adam
    - sampler@tasks.train.data_loaders.train.sampler: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler: subset_random
    - tasks/restore_best_state: restore_best_state
    - tasks/evaluate: test
    - sampler@tasks.evaluate.data_loaders.test.sampler: subset_sequential
